export CUDA_VISIBLE_DEVICES=0
sh ./scripts/MSL/auc.sh
sh ./scripts/PSM/auc.sh
sh ./scripts/SMAP/auc.sh
sh ./scripts/SMD/auc.sh
sh ./scripts/SWAT/auc.sh
sh ./scripts/NIPS_CICIDS/auc.sh
sh ./scripts/NIPS_Creditcard/auc.sh
sh ./scripts/NIPS_GECCO/auc.sh
sh ./scripts/NIPS_SWAN/auc.sh